packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/shared/*'
  - 'libs/api/database-utils'
  - 'libs/api-service/database-utils'
  - 'old'
  - 'tools/prisma'
  - 'libs/api-service/middlewares'
  - 'libs/api-service/auth'
  - 'libs/api-service/auth/*'
  - 'libs/api-service/endpoints/auth/*'
  - 'libs/api-service/utils'
  - 'libs/api-service/*'
  - 'libs/api-service/endpoints/*'
  - 'libs/www/*'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'prisma'
