packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/shared/*'
  - 'libs/api-service/*'
  - 'libs/www/*'
  - 'tools/*'
  - 'libs/admin/*'
  - 'libs/api/*'
  - 'config/*'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'prisma'
